name: five_on_4_mobile
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  mocktail: ^1.0.2
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  hooks_riverpod: ^2.4.9
  # TODO these might be dev dep actually
  path: ^1.8.3
  mocktail_image_network: ^1.0.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logo/
    - assets/images/test/
